version: "3.8"
services:
  mcp-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      ENABLE_UNSAFE_SSE_TRANSPORT: "1"
      PORT: "3001"
    volumes:
      - ~/.kube/config:/home/appuser/.kube/config:ro
